In [5]:
# Lab 1

import numpy as n
# Question.1
#mylist=list(int(input('Enter List:')))
#arr=n.array(mylist)
arr=n.array([1,2,3,4,5])
print('Numpy Array:')
print(arr)


Numpy Array:
[1 2 3 4 5]


In [2]:
# Question.2
arr1=n.array([1,2,3,4,5])
print('First element::',arr1[0])
print('Last element::',arr1[len(arr1)-1])
print('Array after doubling each element::')
print(arr1*2)

First element:: 1
Last element:: 5
Array after doubling each element::
[ 2  4  6  8 10]


In [3]:
# Question.3
arr2=n.zeros(10)
print('An array of 10 zeros::')
print(arr2)
arr3=n.zeros(10)+1
print('An array of 10 ones::')
print(arr3)
arr4=n.zeros(10)+5
print('An array of 10 fives::')
print(arr4)

An array of 10 zeros::
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones::
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives::
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [4]:
# Question.4
arr5=n.arange(2,11).reshape(3,3)
print('Representing an 3x3 array::')
print(arr5)

Representing an 3x3 array::
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
